-- Read-only fixed-cutoff follow-up; output is aggregate JSON without identifiers.
with bounds as (select '2026-06-30T16:00:00Z'::timestamptz as start_at,'2026-09-23T15:27:28.147672Z'::timestamptz as end_at),
c as (select s.id,s.created_at,s.visibility,s.lifecycle_status,case when e.source in('api','mcp','direct') then e.source when coalesce(e.source,'')='' then 'unknown' else 'other' end as source from public.shares s cross join bounds b left join lateral(select metadata->>'source' as source from public.share_events where share_id=s.id and event_type='created' and created_at<=b.end_at order by created_at limit 1)e on true where s.created_at>=b.start_at and s.created_at<=b.end_at),
p as (select c.*,count(e.id) as views,count(e.id) filter(where e.created_at>=c.created_at+interval '24 hour' and e.created_at<c.created_at+interval '7 day') as views_days2to7,count(e.id) filter(where e.created_at>=c.created_at+interval '7 day' and e.created_at<c.created_at+interval '14 day') as views_days8to14,count(distinct (e.created_at at time zone 'Asia/Taipei')::date) filter(where e.created_at<c.created_at+interval '7 day') as dates_in7d from c cross join bounds b left join public.share_events e on e.share_id=c.id and e.event_type='viewed' and e.created_at<=b.end_at group by c.id,c.created_at,c.visibility,c.lifecycle_status,c.source)
select json_build_object(
 'mature_cohorts',(select json_agg(t order by t.month,t.source) from(select to_char(created_at at time zone 'Asia/Taipei','YYYY-MM') as month,source,count(*) filter(where created_at<=b.end_at-interval '7 day') as eligible_7d,count(*) filter(where created_at<=b.end_at-interval '7 day' and views_days2to7>0) as requested_days2to7,count(*) filter(where created_at<=b.end_at-interval '7 day' and dates_in7d>=2) as requested_multiple_dates_in7d,count(*) filter(where created_at<=b.end_at-interval '14 day') as eligible_14d,count(*) filter(where created_at<=b.end_at-interval '14 day' and views_days8to14>0) as requested_days8to14 from p cross join bounds b group by month,source)t),
 'concentration',(select json_build_object('requests',sum(views),'largest_record_requests',max(views),'top5_requests',sum(views) filter(where rnk<=5),'top10_requests',sum(views) filter(where rnk<=10),'top28_requests',sum(views) filter(where rnk<=28)) from(select views,row_number()over(order by views desc) as rnk from p)t),
 'request_age',(select json_agg(t order by t.bucket)from(select case when e.created_at<c.created_at+interval '1 minute' then 'under_1m' when e.created_at<c.created_at+interval '1 hour' then '1m_to_1h' when e.created_at<c.created_at+interval '24 hour' then '1h_to_24h' when e.created_at<c.created_at+interval '7 day' then '1d_to_7d' else '7d_plus' end as bucket,count(*) as requests from c join public.share_events e on e.share_id=c.id cross join bounds b where e.event_type='viewed' and e.created_at<=b.end_at group by bucket)t)
) as analysis;
