-- Add link-key protected shares without changing existing public-unlisted rows.
-- Access keys are generated by the Worker; only their peppered SHA-256 hashes
-- are stored. The row-level consistency check prevents either visibility mode
-- from being persisted with the wrong key state.

alter table public.shares
  add column if not exists access_key_hash text;

alter table public.shares
  add column if not exists access_key_version smallint;

alter table public.shares
  drop constraint if exists shares_visibility_check;

alter table public.shares
  add constraint shares_visibility_check
  check (visibility in ('public_unlisted', 'private_link'));

alter table public.shares
  drop constraint if exists shares_access_key_consistency_check;

alter table public.shares
  add constraint shares_access_key_consistency_check
  check (
    (
      visibility = 'public_unlisted'
      and access_key_hash is null
      and access_key_version is null
    )
    or
    (
      visibility = 'private_link'
      and access_key_hash is not null
      and access_key_hash ~ '^[0-9a-f]{64}$'
      and access_key_version is not null
      and access_key_version = 1
    )
  );

-- RLS controls rows, not columns. Keep browser-authenticated owners from
-- reading credential and infrastructure columns through the Supabase client.
revoke select on table public.shares from authenticated;
grant select (
  id,
  slug,
  owner_user_id,
  share_type,
  title,
  description,
  size_bytes,
  visibility,
  lifecycle_status,
  moderation_status,
  risk_score,
  risk_reasons,
  expires_at,
  created_at,
  updated_at,
  deleted_at
) on table public.shares to authenticated;

-- The original row policy allowed a user to update every profile column,
-- including role. Restrict direct browser updates to the display name only.
revoke update on table public.profiles from authenticated;
grant update (display_name) on table public.profiles to authenticated;
